# Build version format
version: "{build}"

environment:
  matrix:
    - nodejs_version: 8
    - nodejs_version: 10

install:
    # install node
  - ps: Install-Product node $env:nodejs_version
  - npm install

build: off

test_script:
    # no openssl
  - npm run test:openssl
    # install openssl
  - ps: Start-FileDownload 'https://slproweb.com/download/Win64OpenSSL-1_1_1a.exe'
  - ps: Start-Process "Win64OpenSSL-1_1_1a.exe" -ArgumentList "/silent /verysilent /sp- /suppressmsgboxes" -Wait
    # test normally
  - npm run test

matrix:
  fast_finish: true
