# Build version format
version: "{build}"

environment:
  matrix:
    - nodejs_version: 10
    - nodejs_version: 12

install:
    # install node
  - ps: Install-Product node $env:nodejs_version
  - npm install

build: off

test_script:
  - npm run test

matrix:
  fast_finish: true
